version: '3.8'

services:

  backend:
    image: ghcr.io/xyhelper/claude-share-server:dev
    container_name: xyucenter
    ports:
      - "127.0.0.1:8002:8002"
    environment:
      - TZ=Asia/Shanghai
      - CLAUDEPROXY=
      - CALLBACKURL= #本服务回调地址
      - XYUCENTER=  #认证中心地址
      - AUTH0DOMAIN= #Auth0域名
      - AUTH0CLIENTID= #Auth0 客户端 ID
      - AUTH0CLIENTSECRET= #Auth0 客户端密钥
      - APPID= #子应用appid
      - APPSECRET= # 子应用appsecret
      - APPJWTSECRETKEY= #子应用下发token秘钥
     
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    network_mode: host
    volumes:
      - ./backend/manifest:/app/manifest
      - ./backend/certs:/app/certs
      - ./backend/config.yaml:/app/config.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8
    command: --mysql-native-password=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "cool"
      MYSQL_USER: "cool"
      MYSQL_PASSWORD: "123123"
    ports:
      - 127.0.0.1:3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/:/data/
    ports:
      - 127.0.0.1:6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  mysql-data:
  redis-data: 